name: Noriko Foundation
favicon: null
layout_spectrum: 0.3948303849902004
typography_spectrum: 0.6273118080571294
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.40113509097136557
  lightness: 0.42112315515987575
  saturation: 0.7608105146791786
  rhythmicContrast: 0.39795724651776254
purpose: []
